### ISSUE TITLE
Not working on RPI2 B Model (Jessie)

### ISSUE THREAD

**Issue by fireheadman** [nathanpjones/GaragePi#1]
Fresh install of Jessie on RPI2 B model (40 Pin GPIO)
Almost everything installed perfect... Did run into a snag with the SECRET_KEY not generating at the end.  I was able to resolve this by manually running the cmd and redirectly the output to the app.cfg.  I am able to hit webserver page.

I have GPIO pin 7 configured to a relay.   Currently I am seeing not seeing the Open button (when clicked/confirmed) trigger the GPIO pin 7.    To confirm my wiring and hardware, I installed webiopi (w/patch for v1.7.x) and this was able to trigger the relay.

Also worth mentioning is....  The CPU/GPU temps are not registering.

Was hoping this would work, but appears there is something missing, perhaps a config?

**Comment by fireheadman** [comment]
This is the section that fail during install, do not have actual screenshot anymore, but it reported a syntax related error.
```
  # Copy default config file over and generate key if
  # config file doesn't already exist.
  if [ ! -f "${INSTANCE_DIR}/app.cfg" ]; then
    cp "${RESOURCE_DIR}/default_app.cfg" "${INSTANCE_DIR}/app.cfg"
    **python "${SETUP_DIR}/generate_secret_key.py" >> "${INSTANCE_DIR}/app.cfg"**
  fi
```

#cat generate_secret_key.py
```
import os
secret_key = os.urandom(24)
**print "SECRET_KEY = %r" % (secret_key)**
```

**Comment by nathanpjones** [comment]
Ah, this looks like a Python versioning issue. I think Jessie may have changed the default Python interpreter from 2 to 3. I may have to fix the setup script since this project requires 2.

At a fresh terminal type the following and paste the results.

``` bash
python -V
```

**Comment by fireheadman** [comment]
pi@webcam03:~ $ python -V
Python 2.7.9

for Jessie, python3 is installed, but the system still defaults to version 2.x since they have not adopted all OS related objects/scripts to use pure v3.x.

Not sure what is causing the disconnect to make it not run.

**Comment by nathanpjones** [comment]
Hmm. That's the right version. Did you use `sudo` to run the install script? You shouldn't and maybe the root user has a different default for some reason.

That syntax error would be a breaking change introduced with the `print` statement in Python 3.

**Comment by fireheadman** [comment]
did not use sudo, as I recall.... it will prompt that you should not run as sudo?....

The first couple lines say this....
`if [ $(id -u) -eq 0 ]; then
  echo "This should not be run with sudo. Try again without running with sudo."`

**Comment by fireheadman** [comment]
that is in your online_install.sh.    running as sudo would make it exit.
However, I did not run it as root.... I can re-run the script as root and see if that resolves anything...

**Comment by fireheadman** [comment]
looks like running as root is not recommended either:

`root@webcam03:/home/pi/garage_pi/setup# ./online_install.sh
This should not be run with sudo. Try again without running with sudo.`

**Comment by nathanpjones** [comment]
Can you try manually editing `generate_secret_key.py` and changing the line we're having trouble with to this (note the added parentheses).

```python
print("SECRET_KEY = %r" % (secret_key))
```

That should at least get you through the install. I'm worried that when the virtual environment is created it might use the wrong version of python but I guess we'll tackle that when/if it happens.

**Comment by nathanpjones** [comment]
Nevermind. I looked through the setup script and realized that at that point we've already activated the virtual environment and are running in python3. I'll fix the script. In the meantime, the above edit should get you through. I'll keep this issue open until I've pushed a fix.

**Comment by fireheadman** [comment]
So I removed /home/pi/garage_pi completely, then re-ran the cmd you have to perform an online install:

`curl -s "https://raw.githubusercontent.com/nathanpjones/GaragePi/master/setup/online_install.sh" | bash
`

The installation went perfect (no errors).

But still seeing issues:
I have GPIO pin 7 configured to a relay and pin 17 to the reed switch. Currently I am seeing not seeing the Open button (when clicked and confirmed) trigger the GPIO pin 7 (relay is not firing). To confirm my wiring and hardware, I created a simple python script to trigger the pins, along with using the reed switch.  Everything is logically working with this simple script.  

Also worth mentioning is.... The CPU/GPU temps are not registering, I only see a question mark/degrees.

**Comment by fireheadman** [comment]
I have 1 left course of action to take, which I am performing now....    I had a friend lend me his RPI model-A (has the full size sdcard and 26 pin GPIO).  I am installing Wheezy on it and will redo your online install to see if there is any change.   Not really the best test to perform since I am changing the OS and Hardware.

If this proves to be good, then I am in business and I have more time to myself.  Otherwise, I have already started coding a python/web-app using your css (really like your clean setup).

**Comment by nathanpjones** [comment]
I just double-checked and the specific Pi I'm using is a [Raspberry Pi 1 Model B](https://en.wikipedia.org/wiki/Raspberry_Pi#/media/File:Drawing_of_Raspberry_Pi_model_B_rev2.svg) running Jessie. But that shouldn't make a difference for what we're doing here.

So the way this project works is there's a web server in Flask to serve up the web page and handle ajax requests from your browser (you're not blocking scripts are you?). For triggering the open and getting door status and temps your browser makes an ajax request to the web server which in turn passes everything through to a separately running service that actually does the GPIO. This is done for permissions reasons and to allow certain things like checking if your garage door is still open at a certain time.

Without more info it's hard to say which part of that is not working. After a clean boot, run the following command and paste the output here.

```bash
service garagepi status
```

Then try to use the web interface to open the door to get some entries in the log. Attach any `.log` files that you find in your `garagepi/instance` folder.

One last note because from what you said I couldn't tell if you did this or not. The default pin for the reed switch is 18. If you're using pin 17, make sure to change the `REED_PIN` setting in `garagepi/instance/app.cfg`.

**Comment by fireheadman** [comment]
..This output is from my Pi2 B+ w/jessie   (Still building my Pi1 B..... thought it was an A)

`pi@webcam03:~/garage/python $ sudo service garagepi status
● garagepi.service - LSB: Init script for GaragePi
   Loaded: loaded (/etc/init.d/garagepi)
   Active: active (exited) since Sat 2016-06-18 22:22:01 MDT; 1h 53min ago
  Process: 393 ExecStart=/etc/init.d/garagepi start (code=exited, status=0/SUCCESS)

Jun 18 22:21:59 webcam03 systemd[1]: Starting LSB: Init script for GaragePi...
Jun 18 22:22:00 webcam03 garagepi[393]: Starting system garagepi daemon:.
Jun 18 22:22:01 webcam03 systemd[1]: Started LSB: Init script for GaragePi.`

Also, Yes, I have app.cfg configured for reed=17, garage=7.

**Comment by fireheadman** [comment]
another thought/question.  Are you running jessie-lite ?   This is what I have installed since I am headless.

**Comment by fireheadman** [comment]
worth noting:
I scratched my wheezy build after I saw you mentioned you are on jessie.   So fresh install (within an hour using jessie-lite).  After I setup my PI (locale/timezone/overclock/hostname/passwd/ssh enable) and updated OS, I immediately cut/pasted your curl cmd for the online install.

**Round 1** --> "git" isn't installed, so the installer failed....  installed git
**Round 2** --> get an error "Python 3 is required but isn't installed, Easiest way to get it is upgrade to Raspbian Jessie" ....  installed Python3 (including python3-dev)
**Round 3** --> almost completed this time, lighttpd installation aborted, manually installed it
**Round 4** --> garage_pi successfully installs  (pyzmq takes forever on a Pi1 Model B)

- Fired up browser (safari) and opened port 80 --> able to see GaragePi webpage
- Transferred my GPIO connections from my Pi2 to the Pi1 Model B and for sanity reasons, I wired the GPIOs to 7=Garage//18=Reed

**Outcome:**   I get the same thing as on the RPi2 B+.

- The Door Status says Closed (regardless if I move the reed magnet away from the base and refresh the browser)
- The Pi Status shows ?° C for CPU/GPU
- And when clicking the "Open Door" button and "Proceed" button, I do not see or hear the relay triggering

**Comment by nathanpjones** [comment]
Thanks for the excellent work in troubleshooting this. Your logs indicated that the service wasn't running. Looks like it was a rookie Python mistake on my part when checking to see if you have an IFTTT key. Fixed that and added some extra logging around errors.

**Comment by fireheadman** [comment]
oh snap!... Its WORKING NOW!   You da man!

So now I move onto phase 2:

**Webcam Module-**
I already have this working on my prototype.   Adding motionpie to the mix so I can have a visual on the garage (using USB at the moment, but swapping out for a raspi-cam for small form factor).  I simply duplicate your css/div tags to insert another blue container/box to wrap the webcam stream.  This give me ability to open garage for fedex/ups/freight when not home and record them.

**Garage Temperature Module-**
Also implementing a dual DS18B20 (digital temp sensors) circuit onto my side board to retrieve the garage temperature, will just add a python module to collect temps and a new line of code into the html to display the garage temp under your CPU/GPU section.   I like working on projects in the summer/winter, so will be nice to see the temps.

If you are interested in these, I can post them or email them to you.
Absolutely love your GaragePi app now  and appreciate you looking into it.

**Comment by nathanpjones** [comment]
That's great news! I'd love to hear what you do with the project.

Actually, if you feel comfortable doing so I'd encourage you to create a pull request for bringing that functionality into the project. Using the RPi camera was something I always wanted to do, just didn't have the time. Even bringing over the temp sensors would be great. Just try to keep things modular in the code and give people a way to turn things on and off in the app config.

**Comment by fireheadman** [comment]
Here is quick peek at that I have done.   Not sure if you will like everything, if you do... I can do the pull request.

Inserted camera.css, this holds the css for the camera and the toggle for the div hold the stream, tried to use a flat looking css/jquery toggle to match your layout.
changed .open_closed_btn so the open/close button has slightly different corner radius (looks more obvious to be a button)
Cleaned up the html pages (tags) so they indent, found a couple tags that were not being used, removed those, added some additional comments.
Moved the Open/Close button into the main div section since it was splitting off on large screens
Inserted a placeholder for Garage Temperature (still waiting on parts to fabricate the circuit), plan on converting to Fahrenheit and still have Celsius.

As far as making things modular, the camera.css accomplishes that, but would have to do something like a catch tag in the garage_control.html for the installer to uncomment/comment out the camera section (maybe a y/n question to trigger the installer to do this?).

I will be slowly working on more with this as parts arrive.

![image](https://cloud.githubusercontent.com/assets/19847195/16242035/ce2855dc-37ad-11e6-8b7e-dd88f3679e35.png)

**Comment by fireheadman** [comment]
ended up pulling this piece onto my RPi    [https://www.richlynch.com/2013/08/04/pi_garage_alert_2/#comment-2745505819](url)    To get email to SMS notifications when the garage is left open for X number of seconds since I will not want to watch this app all day long.   Works pretty good.    Might be something good to splice into the backend service for your project.

**Comment by nathanpjones** [comment]
I like what you've done. Go ahead and submit a pull request for what you've got. If you like, we can work together on making it modular to turn parts on and off.

**Comment by fireheadman** [comment]
Hey Nathan,

I am slowly adding in additional code for the temperature readings...
having some hangups with modules not importing, once I get that working I
can do a pull request for you.

**Comment by fireheadman** [comment]
Nathan!

I got it working last night... Code may need some refinement.   When the
door is open, it spews open/close signals.
This could be related to my circuit...where I am using a single 3.3v GPIO
pin to drive the reed switch and the temp (x3 - DS18B20) sensors.
Was looking for a place to make the get_garage_temp routine sleep for 5-7
seconds (without effecting the other subroutines), think the 1 poll/sec is
right on the cusp of being too fast, which is backlogging temperature
sensor polling....

Ended up using json output from the w1thermsensor pkg (written by Timo
Furrer -- https://github.com/timofurrer/w1thermsensor)

Trying to figure out how to use GitHub, first time doing this...  I was
trying to create a branch off yours to upload, no luck (might have missed
something??)
So I created a fork and gave you collaborator rights.   IF there is a
better way to do this, let me know.


(Messy Garage -- still moving IN)
[image: Inline image 1]

**Comment by fireheadman** [comment]
here is the fork...   https://github.com/fireheadman/GaragePi
Honestly, I am not liking this setup since I seem to have lost all the
change history when I uploaded via command line.

I saw there is the ability to have an upstream branch off the master, which
would be a good place to push updates/test so that you can merge them from
upstream to master when you are ready.
Just not sure how to set that up.

**Comment by fireheadman** [comment]
played around with this a lot today...learned some more about GITHUB, but
no way an expert.
I ended up deleting my fork/branch.

If phone works better for you, send me a text/call  at 303-525-5302 and
maybe you can walk me through how to setup an upstream/dev branch to
contribute to.

-Ben

**Comment by fireheadman** [comment]
thought of a possible solution to retain performance and keep garTemp piece
working.
Will re-write the block in controller.py to read a file to get the
temperature, which should be fairly quick and will have a separate def
routine() to perform the temp collecting since this takes some time to
collect/parse.

-ben

**Comment by fireheadman** [comment]
I have the re-write completed... its modular now (might need a tad bit of refinement).
/home/pi/garage_pi/backend/collect_garage_temps.py collects temps from DS18B20 sensor(s) and stores readings in /tmp/garage_temp every 5sec.

This script is a daemonized py script that uses systemd (/etc/systemd/system/garage_temp.service) so it is independent of controller.py and it also sends output logger INFO/WARN messages to garage_backend.log on its readings.  

If this script isn't running, the last known/found temp in /tmp/garage_temp will show on the html page.... thinking maybe something else can be coded to reset the value to "--"C / "--"F if a reading is older than 30min or something??

After all this re-writing, I thought this would calm my Reed Switch down, right now when I open my garage, it still spews open/close/open/close...etc..etc, which is making the garage_backend.log grow fast then rotate.   I might back out all my changes to see if I introduced this.
